name: Build and push backend Express image

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths:
      - backend/express

jobs:
  backend-express:
    uses: ./.github/workflows/build-and-push.yml
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    with:
      path: backend/express
      tag: express
      render-deploy-url: ${{ secrets.RENDER_BACKEND_EXPRESS_DEPLOY_HOOK_URL }}