name: Build and push backend Express image

on:
  push:
    branches: ['main']

jobs:
  build-and-push-image:
    uses: ./.github/workflows/backend.yml
    with:
      path: backend/express
      tag: express