name: Build and push frontend React image

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths:
      - frontend/react

jobs:
  frontend-react:
    uses: ./.github/workflows/build-and-push.yml
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    with:
      path: frontend/react
      tag: react
      buildArgs: |
        VITE_APP_TITLE=Deployment workshop (GitHub Actions)