name: Build, push and redeploy frontend React image

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths:
      - frontend/react

jobs:
  frontend-react:
    uses: ./.github/workflows/build-push-and-redeploy.yml
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    with:
      path: frontend/react
      tag: react
      render-deploy-url: ${{ secrets.RENDER_BACKEND_REACT_DEPLOY_HOOK_URL }}
      build-args: |
        VITE_APP_TITLE=Deployment workshop (GitHub Actions)