name: Build, push and redeploy frontend React image

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths:
      - frontend/react/**

jobs:
  frontend-react:
    uses: ./.github/workflows/build-push-and-redeploy.yml
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    with:
      path: frontend/react
      tag: react
      # **Important**: appending trailing / after the URL makes nginx *not* pass a matched location prefix to the proxy, e.g. omits /api
      build-args: |
        VITE_APP_TITLE=Deployment workshop (GitHub Actions)
        UPSTREAM_URL=https://deployment-workshop-asp.onrender.com
    secrets:
      render-deploy-url: ${{ secrets.RENDER_FRONTEND_REACT_DEPLOY_HOOK_URL }}